from pathlib import Path
from config import CODE_OUTPUT_DIR, DATA_DIR
from utils.logger import get_logger

logger = get_logger(__name__)


LANGUAGE_EXTENSIONS = {
    "python": ".py",
    "java": ".java",
    "javascript": ".js",
    "typescript": ".ts",
    "c": ".c",
    "cpp": ".cpp",
    "c++": ".cpp",
    "csharp": ".cs",
    "c#": ".cs",
    "go": ".go",
    "rust": ".rs",
    "php": ".php",
    "ruby": ".rb",
    "swift": ".swift",
    "kotlin": ".kt",
    "html": ".html",
    "css": ".css",
    "json": ".json",
    "sql": ".sql",
    "bash": ".sh",
}


def _slugify(text):
    cleaned = "".join(ch.lower() if ch.isalnum() else "_" for ch in (text or "generated_code"))
    collapsed = "_".join(part for part in cleaned.split("_") if part)
    return (collapsed or "generated_code")[:80]


def _infer_target(target=None, language=None, prompt=None, description=None):
    if target:
        return target

    ext = LANGUAGE_EXTENSIONS.get((language or "").strip().lower(), ".txt")
    name_seed = prompt or description or "generated_code"
    return f"{_slugify(name_seed)}{ext}"


def _fallback_content(language=None, prompt=None, description=None):
    requested = prompt or description or "code requested by the user"
    label = (language or "requested language").strip() or "requested language"
    return (
        f"// Placeholder generated by Aura\n"
        f"// Language: {label}\n"
        f"// Request: {requested}\n"
        f"// No code content was supplied by the agent for this request yet.\n"
    )


def write_code(target=None, content="", root=None, prompt=None, description=None, language=None):
    """Write code to the configured code folder unless another root is provided."""
    try:
        allowed_root = Path(CODE_OUTPUT_DIR).resolve()
        output_root = Path(root).expanduser().resolve() if root else allowed_root
        if output_root != allowed_root:
            raise ValueError(
                f"Code writing is currently limited to the app data folder: {Path(DATA_DIR).resolve()}. "
                "Broader D: or E: access is not enabled yet."
            )
        output_root.mkdir(parents=True, exist_ok=True)

        target = _infer_target(
            target=target,
            language=language,
            prompt=prompt,
            description=description,
        )

        file_path = (output_root / target).resolve()
        if not str(file_path).startswith(str(output_root.resolve())):
            raise ValueError("Invalid output path")

        final_content = content or _fallback_content(
            language=language,
            prompt=prompt,
            description=description,
        )
        file_path.parent.mkdir(parents=True, exist_ok=True)

        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(final_content)
        
        logger.info(f"Wrote code file: {file_path}")
        return {
            "status": "success",
            "message": f"Code written to {file_path}",
            "file_path": str(file_path),
        }
    
    except Exception as e:
        logger.error(f"Failed to write code: {e}")
        raise
